### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by leisurelicht** [lrita/AcFun_Checkin#1]
你好，我想请问下http://www.acfun.tv/login.aspx和http://www.acfun.tv/member/checkin.aspx这两个网址你是怎么找到的？

**Comment by lrita** [comment]
打开FIREFOX的Firebug、Chrome的F12键激活开发者模式，就能看到你页面的每个操作都调用了哪些URL，传了什么参数。
或者用Wireshark抓包看。

**Comment by leisurelicht** [comment]
但是我在抓的时候抓到的是两个POST数据，签到抓到的是`webapi.acfun.tv/record/actions/signin?channel=0&date=1456229589926 `，登录是`http://passport.acfun.tv/login.aspx`。不论是页面中还是发包过程中都找不到那里调用了`http://www.acfun.tv/login.aspx`和`http://www.acfun.tv/member/checkin.aspx`这两个url。

**Comment by lrita** [comment]
我的这个是很早之前的了，可能已经过期了。
网站改版，很多URL都会变化的。
